python baseline.py --dataset cora --mode A --ad-method IF
python baseline.py --dataset cora --mode X --ad-method IF 
python baseline.py --dataset cora --mode AX --ad-method IF 
python baseline.py --dataset cora --mode A --ad-method OCSVM
python baseline.py --dataset cora --mode X --ad-method OCSVM
python baseline.py --dataset cora --mode AX --ad-method OCSVM
python baseline.py --dataset cora --mode A --ad-method PCA
python baseline.py --dataset cora --mode X --ad-method PCA
python baseline.py --dataset cora --mode AX --ad-method PCA
python baseline.py --dataset citeseer --mode A --ad-method IF
python baseline.py --dataset citeseer --mode X --ad-method IF 
python baseline.py --dataset citeseer --mode AX --ad-method IF 
python baseline.py --dataset citeseer --mode A --ad-method OCSVM
python baseline.py --dataset citeseer --mode X --ad-method OCSVM
python baseline.py --dataset citeseer --mode AX --ad-method OCSVM
python baseline.py --dataset citeseer --mode A --ad-method PCA
python baseline.py --dataset citeseer --mode X --ad-method PCA
python baseline.py --dataset citeseer --mode AX --ad-method PCA
python baseline.py --dataset pubmed --mode A --ad-method IF
python baseline.py --dataset pubmed --mode X --ad-method IF 
python baseline.py --dataset pubmed --mode AX --ad-method IF 
python baseline.py --dataset pubmed --mode A --ad-method OCSVM
python baseline.py --dataset pubmed --mode X --ad-method OCSVM
python baseline.py --dataset pubmed --mode AX --ad-method OCSVM
python baseline.py --dataset pubmed --mode A --ad-method PCA
python baseline.py --dataset pubmed --mode X --ad-method PCA
python baseline.py --dataset pubmed --mode AX --ad-method PCA