python main.py --dataset pubmed --gpu 1 --module GAT  --n-layers 1 --n-hidden 16
python main.py --dataset pubmed --gpu 1 --module GAT  --n-layers 2 --n-hidden 16
python main.py --dataset pubmed --gpu 1 --module GAT  --n-layers 3 --n-hidden 16
python main.py --dataset pubmed --gpu 1 --module GAT  --n-layers 4 --n-hidden 16
python main.py --dataset pubmed --gpu 1 --module GAT  --n-layers 5 --n-hidden 16
python main.py --dataset pubmed --gpu 1 --module GAT  --n-layers 6 --n-hidden 16
python main.py --dataset pubmed --gpu 1 --module GAT  --n-layers 7 --n-hidden 16
python main.py --dataset pubmed --gpu 1 --module GAT  --n-layers 1 --n-hidden 32
python main.py --dataset pubmed --gpu 1 --module GAT  --n-layers 2 --n-hidden 32
python main.py --dataset pubmed --gpu 1 --module GAT  --n-layers 3 --n-hidden 32
python main.py --dataset pubmed --gpu 1 --module GAT  --n-layers 4 --n-hidden 32
python main.py --dataset pubmed --gpu 1 --module GAT  --n-layers 5 --n-hidden 32
python main.py --dataset pubmed --gpu 1 --module GAT  --n-layers 6 --n-hidden 32
python main.py --dataset pubmed --gpu 1 --module GAT  --n-layers 7 --n-hidden 32
python main.py --dataset pubmed --gpu 1 --module GAT  --n-layers 1 --n-hidden 64
python main.py --dataset pubmed --gpu 1 --module GAT  --n-layers 2 --n-hidden 64
python main.py --dataset pubmed --gpu 1 --module GAT  --n-layers 3 --n-hidden 64
python main.py --dataset pubmed --gpu 1 --module GAT  --n-layers 4 --n-hidden 64
python main.py --dataset pubmed --gpu 1 --module GAT  --n-layers 5 --n-hidden 64
python main.py --dataset pubmed --gpu 1 --module GAT  --n-layers 6 --n-hidden 64
python main.py --dataset pubmed --gpu 1 --module GAT  --n-layers 7 --n-hidden 64
python main.py --dataset pubmed --gpu 1 --module GAT  --n-layers 1 --n-hidden 128
python main.py --dataset pubmed --gpu 1 --module GAT  --n-layers 2 --n-hidden 128
python main.py --dataset pubmed --gpu 1 --module GAT  --n-layers 3 --n-hidden 128
python main.py --dataset pubmed --gpu 1 --module GAT  --n-layers 4 --n-hidden 128
python main.py --dataset pubmed --gpu 1 --module GAT  --n-layers 5 --n-hidden 128
python main.py --dataset pubmed --gpu 1 --module GAT  --n-layers 6 --n-hidden 128
python main.py --dataset pubmed --gpu 1 --module GAT  --n-layers 7 --n-hidden 128
 
python main.py --dataset pubmed --gpu 1 --module GraphSAGE --n-layers 1 --n-hidden 16
python main.py --dataset pubmed --gpu 1 --module GraphSAGE --n-layers 2 --n-hidden 16
python main.py --dataset pubmed --gpu 1 --module GraphSAGE --n-layers 3 --n-hidden 16
python main.py --dataset pubmed --gpu 1 --module GraphSAGE --n-layers 4 --n-hidden 16
python main.py --dataset pubmed --gpu 1 --module GraphSAGE --n-layers 5 --n-hidden 16
python main.py --dataset pubmed --gpu 1 --module GraphSAGE --n-layers 6 --n-hidden 16
python main.py --dataset pubmed --gpu 1 --module GraphSAGE --n-layers 7 --n-hidden 16
python main.py --dataset pubmed --gpu 1 --module GraphSAGE --n-layers 1 --n-hidden 32
python main.py --dataset pubmed --gpu 1 --module GraphSAGE --n-layers 2 --n-hidden 32
python main.py --dataset pubmed --gpu 1 --module GraphSAGE --n-layers 3 --n-hidden 32
python main.py --dataset pubmed --gpu 1 --module GraphSAGE --n-layers 4 --n-hidden 32
python main.py --dataset pubmed --gpu 1 --module GraphSAGE --n-layers 5 --n-hidden 32
python main.py --dataset pubmed --gpu 1 --module GraphSAGE --n-layers 6 --n-hidden 32
python main.py --dataset pubmed --gpu 1 --module GraphSAGE --n-layers 7 --n-hidden 32
python main.py --dataset pubmed --gpu 1 --module GraphSAGE --n-layers 1 --n-hidden 64
python main.py --dataset pubmed --gpu 1 --module GraphSAGE --n-layers 2 --n-hidden 64
python main.py --dataset pubmed --gpu 1 --module GraphSAGE --n-layers 3 --n-hidden 64
python main.py --dataset pubmed --gpu 1 --module GraphSAGE --n-layers 4 --n-hidden 64
python main.py --dataset pubmed --gpu 1 --module GraphSAGE --n-layers 5 --n-hidden 64
python main.py --dataset pubmed --gpu 1 --module GraphSAGE --n-layers 6 --n-hidden 64
python main.py --dataset pubmed --gpu 1 --module GraphSAGE --n-layers 7 --n-hidden 64
python main.py --dataset pubmed --gpu 1 --module GraphSAGE --n-layers 1 --n-hidden 128
python main.py --dataset pubmed --gpu 1 --module GraphSAGE --n-layers 2 --n-hidden 128
python main.py --dataset pubmed --gpu 1 --module GraphSAGE --n-layers 3 --n-hidden 128
python main.py --dataset pubmed --gpu 1 --module GraphSAGE --n-layers 4 --n-hidden 128
python main.py --dataset pubmed --gpu 1 --module GraphSAGE --n-layers 5 --n-hidden 128
python main.py --dataset pubmed --gpu 1 --module GraphSAGE --n-layers 6 --n-hidden 128
python main.py --dataset pubmed --gpu 1 --module GraphSAGE --n-layers 7 --n-hidden 128

python main.py --dataset pubmed --gpu 1 --module GIN --n-layers 1 --n-hidden 16
python main.py --dataset pubmed --gpu 1 --module GIN --n-layers 2 --n-hidden 16
python main.py --dataset pubmed --gpu 1 --module GIN --n-layers 3 --n-hidden 16
python main.py --dataset pubmed --gpu 1 --module GIN --n-layers 4 --n-hidden 16
python main.py --dataset pubmed --gpu 1 --module GIN --n-layers 5 --n-hidden 16
python main.py --dataset pubmed --gpu 1 --module GIN --n-layers 6 --n-hidden 16
python main.py --dataset pubmed --gpu 1 --module GIN --n-layers 7 --n-hidden 16
python main.py --dataset pubmed --gpu 1 --module GIN --n-layers 1 --n-hidden 32
python main.py --dataset pubmed --gpu 1 --module GIN --n-layers 2 --n-hidden 32
python main.py --dataset pubmed --gpu 1 --module GIN --n-layers 3 --n-hidden 32
python main.py --dataset pubmed --gpu 1 --module GIN --n-layers 4 --n-hidden 32
python main.py --dataset pubmed --gpu 1 --module GIN --n-layers 5 --n-hidden 32
python main.py --dataset pubmed --gpu 1 --module GIN --n-layers 6 --n-hidden 32
python main.py --dataset pubmed --gpu 1 --module GIN --n-layers 7 --n-hidden 32
python main.py --dataset pubmed --gpu 1 --module GIN --n-layers 1 --n-hidden 64
python main.py --dataset pubmed --gpu 1 --module GIN --n-layers 2 --n-hidden 64
python main.py --dataset pubmed --gpu 1 --module GIN --n-layers 3 --n-hidden 64
python main.py --dataset pubmed --gpu 1 --module GIN --n-layers 4 --n-hidden 64
python main.py --dataset pubmed --gpu 1 --module GIN --n-layers 5 --n-hidden 64
python main.py --dataset pubmed --gpu 1 --module GIN --n-layers 6 --n-hidden 64
python main.py --dataset pubmed --gpu 1 --module GIN --n-layers 7 --n-hidden 64
python main.py --dataset pubmed --gpu 1 --module GIN --n-layers 1 --n-hidden 128
python main.py --dataset pubmed --gpu 1 --module GIN --n-layers 2 --n-hidden 128
python main.py --dataset pubmed --gpu 1 --module GIN --n-layers 3 --n-hidden 128
python main.py --dataset pubmed --gpu 1 --module GIN --n-layers 4 --n-hidden 128
python main.py --dataset pubmed --gpu 1 --module GIN --n-layers 5 --n-hidden 128
python main.py --dataset pubmed --gpu 1 --module GIN --n-layers 6 --n-hidden 128
python main.py --dataset pubmed --gpu 1 --module GIN --n-layers 7 --n-hidden 128


python main.py --dataset pubmed --gpu 1 --module GCN --n-layers 1 --n-hidden 16
python main.py --dataset pubmed --gpu 1 --module GCN --n-layers 2 --n-hidden 16
python main.py --dataset pubmed --gpu 1 --module GCN --n-layers 3 --n-hidden 16
python main.py --dataset pubmed --gpu 1 --module GCN --n-layers 4 --n-hidden 16
python main.py --dataset pubmed --gpu 1 --module GCN --n-layers 5 --n-hidden 16
python main.py --dataset pubmed --gpu 1 --module GCN --n-layers 6 --n-hidden 16
python main.py --dataset pubmed --gpu 1 --module GCN --n-layers 7 --n-hidden 16
python main.py --dataset pubmed --gpu 1 --module GCN --n-layers 1 --n-hidden 32
python main.py --dataset pubmed --gpu 1 --module GCN --n-layers 2 --n-hidden 32
python main.py --dataset pubmed --gpu 1 --module GCN --n-layers 3 --n-hidden 32
python main.py --dataset pubmed --gpu 1 --module GCN --n-layers 4 --n-hidden 32
python main.py --dataset pubmed --gpu 1 --module GCN --n-layers 5 --n-hidden 32
python main.py --dataset pubmed --gpu 1 --module GCN --n-layers 6 --n-hidden 32
python main.py --dataset pubmed --gpu 1 --module GCN --n-layers 7 --n-hidden 32
python main.py --dataset pubmed --gpu 1 --module GCN --n-layers 1 --n-hidden 64
python main.py --dataset pubmed --gpu 1 --module GCN --n-layers 2 --n-hidden 64
python main.py --dataset pubmed --gpu 1 --module GCN --n-layers 3 --n-hidden 64
python main.py --dataset pubmed --gpu 1 --module GCN --n-layers 4 --n-hidden 64
python main.py --dataset pubmed --gpu 1 --module GCN --n-layers 5 --n-hidden 64
python main.py --dataset pubmed --gpu 1 --module GCN --n-layers 6 --n-hidden 64
python main.py --dataset pubmed --gpu 1 --module GCN --n-layers 7 --n-hidden 64
python main.py --dataset pubmed --gpu 1 --module GCN --n-layers 1 --n-hidden 128
python main.py --dataset pubmed --gpu 1 --module GCN --n-layers 2 --n-hidden 128
python main.py --dataset pubmed --gpu 1 --module GCN --n-layers 3 --n-hidden 128
python main.py --dataset pubmed --gpu 1 --module GCN --n-layers 4 --n-hidden 128
python main.py --dataset pubmed --gpu 1 --module GCN --n-layers 5 --n-hidden 128
python main.py --dataset pubmed --gpu 1 --module GCN --n-layers 6 --n-hidden 128
python main.py --dataset pubmed --gpu 1 --module GCN --n-layers 7 --n-hidden 128